import = [
	"~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
]

[window]
padding = { x = 9, y = 7}
decorations = "None"
opacity = 0.8

[scrolling]
history = 50000

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "SemiBold"}
size = 12

[colors]
draw_bold_text_with_bright_colors = true
