[settings]
auto_install = false
cache_prune_age = "10d"
exec_auto_install = false
experimental = true
fetch_remote_versions_timeout = "1m"
go_default_packages_file = "/home/aritro/.config/mise/default-go-packages"
go_set_gobin = false
http_timeout = "1m"
idiomatic_version_file = false
not_found_auto_install = false
plugin_autoupdate_last_check_duration = "1d"

[settings.erlang]
compile = true

[settings.python]
compile = true

[settings.status]
missing_tools = "never"

[tools]
"asdf:birros/asdf-binaryen" = "latest"
"asdf:jtakakura/asdf-odin" = "latest"
bun = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
gleam = "latest"
go = "latest"
hadolint = "latest"
lua-language-server = "latest"
opam = "latest"
usage = "latest"
wasmtime = "latest"
zig = "latest"
