[settings]
experimental = true
python_compile = true

[tools]
usage = "latest"
deno = "latest"
elixir = "latest"
go = "latest"
erlang = "latest"
lua-language-server = "latest"
gleam = "latest"
odin = "latest"
